development:
  adapter: postgresql
  encoding: unicode
  database: driver_development
  host: localhost
  pool: 5
  username: esteban
  password: 

test:
  adapter: postgresql
  encoding: unicode
  database: driver_test
  host: localhost
  pool: 5
  username: esteban
  password: 

production:
  adapter: postgresql
  encoding: unicode
  database: driver_production
  host: localhost
  pool: 5
  username: esteban
  password: your_password