development:
  adapter: postgresql
  encoding: unicode
  database: driver_development
  host: localhost
  pool: 5
  username: esteban
  password: 

test:
  adapter: postgresql
  encoding: unicode
  database: driver_test
  host: localhost
  pool: 5
  username: esteban
  password: 

production:
  adapter: postgresql
  encoding: unicode
  database: d4mdjj4nlurf5e
  host: ec2-54-210-128-153.compute-1.amazonaws.com
  pool: 5
  username: nxmawpwuhfrhui
  password: 23500608f6867845d8eb928f0f656ba84cd4873916820b1afcbf3f533cfbdafa
